sudo: required
services:
    - docker

before_install:
    - docker build -t nicodemusmaurits/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nicodemusmaurits/react-test npm test

after_success:
    - docker build -t nicodemusmaurits/multi-client ./client
    - docker build -t nicodemusmaurits/multi-nginx ./nginx
    - docker build -t nicodemusmaurits/multi-server ./server
    - docker build -t nicodemusmaurits/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push nicodemusmaurits/multi-client
    - docker push nicodemusmaurits/multi-nginx
    - docker push nicodemusmaurits/multi-server
    - docker push nicodemusmaurits/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-675529877763
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY